const getSentence = () => {
    const sentences = ['Te amo mi princesa', 
    'Sabias que cuando te miro me haces sentir en otro mundo', 
    'Eres la unica que siempre va a estar en mi corazon', 
    'Me encantan tu hermosa carita', 'Eres una persona increible', 
    'AMOR... TE AMO MAS QUE A MI VIDA', 'Me encantas cuando te ries', 
    'Estando contigo mi mundo es mejor', 'Eres la mejor parte de mi vida', 
    'Te conoci y descubri el verdadero amor', 'Eres mi Felicidad', 
    'La unica persona que sin hacer nada me vuelve loco.. Te Amo', 
    'Que sepas que mi sonrisa te tiene a ti como motivo', 
    'La gente se combina, pero tú me completas', 
    'No sabes la felicidad que me causa saber que estoy con la mejor persona del mundo', 
    'Le doy gracias a Dios por haberme creado gracias a el tengo el gran honor de compartir con la mejor persona del mundo', 
    'Si supieras que cuando no estoy contigo me deprimo', 
    'Te amo porqué se que a tu lado viviré los mejores momentos de mi vida', 
    'Dicen que no existe una persona perfecta, pero te digo algo, tu lo eres', 
    'Yoteamo así, sin comas, sin espacios y sin punto final', 
    'Todas las cosas que he querido no se compara al amor que siento por ti', 
    'Te miro a los ojos y me enamoras mucho mas... espera, ya estoy enamorado jeje', 
    'Si fuera por mi ya estaria casado mi amor', 'TEAMOMUCHISIMO', 
    'No existe palabra alguna que describa cuanto te amo', 
    'Eres una persona unica, nunca cambies, me enamoras', 
    '!Te quiero Comer a besos mi amorcito!', 
    'Te extaño mucho :(', 
    'Eres muy importante para mi', 
    'Eres mi bebe, mi mundo, mi todo, mi joya, en si todo las palabras bonitas que existen', 
    'Nosotros formamos una pareja perfecta', 
    'Mi bebe eres mi inspiracion de seguir trabajando', 
    'Quiero tener un futuro contigo', 
    'Todas las cosas malas se arreglan si estas conmigo', 
    'Me encanta tus hermosos labios', 
    'Recuerda que esto lo programo la persona que te ama', 
    'Infinidades de oraciones estoy haciendo, pero mi amor por ti todavia lo supera', 
    'No sabes cuanto me hace falta tus abrazos', 
    'Gracias mi princesa por hacerme feliz', 
    'Eres mi inspiracion', 
    'Eres mi musica, que me causa un mundo de emocion cuando te escucho', 
    'Cuando me dices TEAMO me llenas de felicidad', 
    'Gracias por dedicarte a hacernos felices', 
    'Tú eres siempre la respuesta cuando me preguntan que estoy pensando', 
    'TODO MI MUNDO SE BASAN EN 3 COSAS.. DIOS MI FAMILIA Y LA MAS HERMOSA.. TU', 
    'Si supieras cuanto me duelen los dedos de tanto escribir lo que siento por ti jeje', 
    'No necesito a mas chicas en mi vida cuando mi verdadero amor es contigo', 
    'Cuando te veo me llenas de alegria', 
    'Aunque estes lejos de mi siempre me la paso pensando en ti',
    'Eres lo unico que se me viene a la mente',
    'Quizas no te escriba mucho bebe, pero mientras no te escribo trabajo por nuestro futuro',
    'Tu amor es el mío',
    'Cuando nos casemos, disfrutaremos todo lo que Dios nos ofrece',
    'Es impresionante la hermosura que puedes poseer',
    'Gracias a ti descubrí lo que es una amistad verdadera',
    'Esta noche me acostaré temprano para soñarte más tiempo',
    'La distancia impide un beso o un abrazo, pero jamás impide un sentimiento',
    'Me siento como que puedo conquistar el mundo con una mano cuando me estás dando la otra mano',
    'Todo lo que esta escrito aqui me sale del corazon, y del dolor de cabeza al tratar de expresarlo jeje',
    'Me debes un te amo por cada suspiro y un beso por cada segundo que no estás junto a mí',
    'Las verdaderas historias de amor no tienen final, nosotros estamos en esa',
    'La mejor pelicula de amor y romance es la que vivo contigo',
    'Cuando me dicen, componga una cancion en Fa menor pienso en ti para sacar 20',
    'Aunque no te creas, tambien tengo pena',
    'Eres una hermosura y estas wenota',
    'Amo cuando sonries',
    'Amor eres una poesia viviente',
    'Admiro tu forma de ser original',
    'Si me dan un deseo de escoger a cualquier mujer del mundo sin duda te eligiria a ti',
    'Gracias por ser tan cariñosa conmigo',
    'Nunca me cansare de decirte, !TEAMO!',
    'Te compuse muchas canciones solo que me encanta ser detallista',
    'Te quiero comer a besos bebe, como hacemos?',
    'Nunca te vas a imaginar cuantas oraciones estoy haciendo para ti',
    'Amor......... !TE AMO!',
    'Conocerte fue una de las mejores estapas de mi vida',
    'Si me dices TEAMO 10000000000 veces me caso contigo... mentira asi sea que me lo digas una vez igual me caso contigo',
    'Existen muchas palabras bonitas para dedicarte, pero ninguna llega al nivel a donde te lo quiero expresar',
    'Disfruto las tardes cuando estoy junto a ti',
    '¿Qué es un suspiro?, dicen que es el aire que nos sobra, por alguien que nos falta',
    'Yo ya te había besado con los ojos mil veces mientras tú me besabas con los labios por primera vez',
    'Ya que estamos de paso, dejemos huellas bonitas.. shi?',
    'Eres muy calladita, pero aunque seas silenciosa, a veces rompes la barrera de sonido',
    'No sabes cuanto quisiera tenerte conmigo',
    'TEAMOMUCHISIMO mas que mis errores ortograficos',
    'Quisiera verte desatada cuando nos casemos (carita pervertida)',
    'Existe un 0.5% a que aparezaca este mensaje pero si es asi te quiero decir que !te amo mucho!',
    'Soy muy meloso y lo seguire siendo hasta que el pico y la pala nos separe',
    'Me llenas de orgullo mi bebe',
    'Let me love you.. en su tradiccion significa, (dejame amarte)',
    'Te tratare como una reina',
    'Quiero que seamos felices y lo seremos, ya veras',
    'La programacion es algo compleja pero cuando descubres de lo que es capaz te enamora, asi eres tu',
    '5000000 lineas de codigo no alcanzaria para expresarte lo que siento',
    'BEBE, no sabes de lo que soy capaz de hacer por ti',
    'Un spoiler tu cancion esta lista, pero falta cantarla jeje',
    'Me volvi millonario cuando te conoci al saber el valor que tienes para mi',
    'Soy tan afortunado de tenerte, mas que novia, como una mejor amiga',
    'Te quisiera abrazar y no soltarte',
    'No se que le voy a decir a tu papi cuando llegue AAAAA!!!!',
    'Esta aplicacion esta dedicada 100% a ti mi bebe',
    'Quiero bailar contigo :)',
    'El mejor regalo que me dio Dios fue el haberte conocido',
    'Te daria penita caerte a latasos en la calle? MMMMM',
    'Mi princesaaaaaaaa te quiero ver',
    'No hace falta que te recuerde que te amo, pero es que me gusta tanto decírtelo una y otra vez y verte sonreír',
    'Dicen que los mejores momentos llegan cuando menos te lo esperas, y eso es lo que sucedió con nuestro primer beso',
    'Quiero que cuando seamos ancianos, un día me despierte contigo y te diga: ¿Ves? Te prometí que estaria contigo por siempre',
    'Mi primer beso contigo no fue con los labios, sino con la mirada',
    'Bien sabe la luna cuántas noches he estado pensando en cómo enamorarte, y lo mejor paso, que estas conmigo',
    'Trato de ser la mejor persona para ti amorcito',
    'Te diría tantas cosas mirándote, pero muchas más susurrándote (carita pervertida) ok no jaja',
    'Hay días que te extraño. En cambio, otros... también te extraño',
    'Cuando veas que me callo, mírame a los ojos, pues mi mirada te lo dirá todo :) secretos ya revelados',
    'Sueño tanto contigo que mi cama ya sabe quién eres. De hecho, todas las noches me pregunta por ti jaja no mentira',
    'Esperare por ti, y siempre lo hare, confia en mi bebe porque no pienso ir a ningun lugar, si no, esperarte',
    'Quiero casarme contigo :)',
    'Todo lo que quiero es tener una vida junto a ti con Dios, ser millonarios juntos y sacar a nuestras familias adelante',
    'Siempre lo dire, termine con la mejor persona del mundo!',
    'Gracias por estar conmigo y apoyarme en todo',
    'Quiero ver una pelicula contigo, tu y yo solos tomando una taza de chocolate y un pedazo pan',
    'Eres mi joya que siempre a pesar de lo que pase estaras en mi corazon',
    'Nos casamos en 2025 va?',
    'Te amo tanto como si multiplicaras el tamaño en milimetros de 1000 planetas ',
    'Te voy a comprar un telefono :)',
    'Haz mirado una rosa? una de las flores mas hermosas del mundo, tu eres asi..',
    'Tu eres una de las mejores persona que he conocido en mi vida',
    'Si me dijeran, que cambiaria de mi pasado?, diria nada, gracias a todo lo que paso termine con la mejor persona del mundo',
    'Mi princesa si supieras que te amo, mas de lo que te imaginas',
    'Un dia estaremos en una picina como after 3 (carita pervertida) jeje',
    'No se como termine con la mejor persona del mundo',
    'Tienes mas valor que todos los diamantes juntos del mundo',
    'Si te soy sincero... ME ENCANTA COMO ERES',
    'Todo lo haria por ti mi bebe',
    'Te quiero ofrecer un futuro estable con buena estabilidad economica, que puedas comprar lo que quieras y ser felices',
    'No sabes el orgullo que tengo en decir que tengo la mejor princesa a mi lado',
    'Supuestamente nadie sabe que somos novios, cuando te fuistes todo el mundo me dijo, como esta la novia? jaja',
    'BEBEE!!!!!!!! Porque eres tan linda',
    'Mi bebe contigo descubri mi felicidad',
    'Nunca te quisiera perder mi princesa',
    'Hare lo posible para que seas la mas feliz de este planeta',
    'Gracias por darme una oportunidad.... Me hiciste cambiar mucho amor',
    'Siempre lo dire, termine con la mejor persona del mundo',
    'Pueden existir millones de parejas en el mundo pero si te puedo decir algo... nosotros destacamos',
    'Cuando me miras con tus hermosos ojitos, me encata!',
    'Es hermoso cuando muchos hombres te desean y no pueden hacer nada porque estoy yo contigo bebe',
    'Estar contigo es como un pentagrama.. Millones de notas para expresar lo que uno siente, pero conmigo le faltan notas',
    'Eres mi felicidad mi mundo mi todo, todo li quiero tener junto a ti sueños hermosos',
    'Cuando nos casemos iremos a comer helado todos los viernes y compraremos ropa tambien',
    'Las personas me dicen disfruta tu juventud, y yo la disfruto, estando junto a ti',
    'Me da rabia cuando alguien te tira los perros frente mio',
    'Las nalgas me van a quedar cuadradas de tanto escribir aqui en la computadora jaja',
    'Amorcito te dire algo.. Admiro tu cuerpo',
    'Voy a programar algo para caernos a beso un dia de estos jeje ok no',
    'Entreno para ti mi princesa',
    'Quisiera un dia hablar todo el dia junto a ti',
    'En en silencio de mi voz esta el decirte TE AMO publicamente',
    'Te amo mi nena, gracias por estar conmigo siempre en las buenas y en las malas',
    'No soy compositor soy musico, pero tu me haces ser compositor',
    'Disculpame si alguna vez hice algo que te hirio',
    'Siempre estare para ti en las buenas y en las malas',
    'Un verso que se me ocurrio ahorita, Tu felicidad me interesa mas que la mia',
    'Eres hermosa, bella, eres unica, eres una joya, no quiero conocer a nadie mas si no es a ti',
    'Cuando le diras suegrito a mi papa?',
    'AMOR A VECES ME DA PENA HABLAR CON TU PAPA',
    'Un dia sacare una electro de nosotros',
    'Un dia nos vamos a desatar',
    'AMOR me gustas mucho! no importa nada.. me gustas y me enamoras y me vuelves lo-co',
    'Quiero un dia llegar a la iglesia teniendote agarrado de mi mano',
    'Me encantaria ir a la playa y disfrutar del sol contigo',
    'Te enseñare todo lo que se',
    'Solo pienso en ti cuando te veo',
    'Te cuento un secretetito?? pues mejor no jaja',
    'Amorcito si tuvieras la oportunidad de expresarte conmigo que me dirias?',
    'Pienso en ti cada vez que me levanto de la cama',
    'Existe millones de palabras que te puedo decir, pero la palabra que siento por ti no existe es algo unico',
    'Nunca crei sentir tanto amor por una persona',
    'Cuando nos casemos vamos hacer ejercicio juntos si va??',
    'Me gustaria besarte en la calle frente a todos alguna vez',
    'Eres hermosa en todos los sentidos mi bebe, me enamoras mi preciosura',
    'Porque te da penita estar en short frente mio? jeje me encanta tus piernistas blanquitas',
    'Gracias por soportarme mi bebe, soy fastidioso, pero no un fastidioso cualquiera, un fastidioso con estilo',
    '100% ESTA APLICACION DEDICADA A TI PARA QUE PIERDAS EL TIEMPO CUANDO QUIERAS',
    'Si supueras cuanto tiempo estoy aqui sentado jaja',
    'Todo sale aleatorio mi bebe :) para que nunca te canses',
    'Quisiera estar acostado junto a ti y ver una pelicula juntos',
    'Mi princesa eres incrible',
    'Si me dicen que fue lo mas hermoso que me paso en mi vida puedo responder con sinceridad.. y fue conocerte',
    'A veces me frustro por cosas bebe pero te doy gracias porque me levantas el animo',
    'Dios sabe que te AMO MAS QUE A MI VIDA',
    'AMO A DIOS gracias a el descubri que tengo un proposito.. hacerte feliz',
    'Un dia pasaremos de vacaciones en los hoteles mas caros de Caracas',
    'Tu amor es incrible',
    'ME ENCANTA QUE SEAS TAN CARIÑOSA',
    'Tu sabes quien es la mas hermosa de este mundo? lee la primera palabra',
    'Me llenas de emocion al saber que eres mi novia',
    'Cuando nos casemos me las cobro todas',
    'UN BECHITO TELEFONICO A DISTANCIA',
    'Te AM0 c0mTo d0 I0 K3 I`M',
    'Amor no te negare que cuando te vas sin mi, me dan ganas de caerte a besos en la calle y que el mundo lo sepa jaja',
    'Un libro de amor... nunca me los lei pero dicen que es bonito JAJA',
    'Eres unas de las mejores personas del mundo, tienes hermosos sentimientos',
    'Te defendere hasta la muerte',
    'Pase lo que pase siempre te amare igual',
    'Esta es la linea de codigo numero 200 si pasas por aqui pues, te dire que quisiera violarte con cariño cuando nos casemos',
    'Perdon si hice algo que no te gustara bebe',
    'Quisiera cambiar por ti',
    'Me importa mas tu felicidad que la mia mi bebe',
    'Tu voz se escucha cuchi en los audios mi amor, me encanta',
    '!Mi chiquita! eres increible',
    'Daria mi vida por ti',
    'Eres un mundo de felicidad para mi',
    'Eres la chica mas hermosa que he conocido, en todos los sentidos',
    'Eres un Shock de emociones cuando te abrazo',
    '!ME ENCANTAS!',
    'Esta aplicacion es para cuando no tengas nada que hacer jeje',
    'Quizas pasen muchos años pero mi amor por ti seguira siendo el mismo',
    'Gracias por toda la paciencia que has tenido conmigo',
    'Me vuelves LO-CO',
    'Conoceremos las hermosuras que hizo Dios viajando por el mundo',
    'El mayor regalo que alguien podria hacer por mi, es que te pueda ver',
    'Me encanta tu hermosa carita',
    '!AMOR! ERES LO MEJOR QUE ME PUDO HABER PASADO EN LA VIDA',
    'No te merezco mi bebe, eres muy perfecta para mi',
    'Todas las cosas que escribi son aleatorias :) TEAMOMUCHO',
    'Te amo con todas las fuerzas del mundo, aunque bien lo sabes, no me canso de repetírtelo',
    'Eres quien siempre quise, eres quien siempre quiero, eres quien siempre querré, eres la persona de mis sueños',
    'Gracias por quererme, por dedicarme tu tiempo, por hacerme un ladito dentro de tu corazón',
    '¡El mejor café para mis insomnios está en tus ojos!, Hasta yo me quede sorprendido de esas palabras jaja',
    'Lo que quiero contigo, no lo quiero con nadie más mi bebe',
    'Y si volviera a nacer, correría a buscarte por todo el mundo :)',
    'Contigo hasta donde sea nena, hasta lo más oscuro y terrible o hasta el cielo, pero siempre contigo',
    'Pase lo que pase, yo siempre te amare',
    'Eres eso que no quiero perder nunca',
    'Me gustas en todas tus versiones, la alegre, la triste, la enfadada y la feliz, me falta conocer la molesta :)',
    'TE AMO porque me encantas, y eso nadie lo va a cambiar',
    'Caminar de tu mano, es un sueño... mi sueño, un dia vamos hacerlo',
    'Quiero comer un helado contigo en un parque, ir a la playa y amarte por siempre',
    'Se que suelo ser un poco fastidioso :(',
    'Me encanta tu hermosa voz',
    'Cantas hermoso mi princesa',
    '!Te extraño mucho! aunque no creas escribo esto y me pongo !SAD!',
    'Me encanta cuando me escribes TEAMO lo admito',
    'I LOVE YOU, TE AMO, Je t`aime, TI AMO, muchas formas de decirte TEAMO :)',
    'MI CHIQUITA QUE TAL SI NOS VEMOS UNA PELICULA JUNTOS SHI?',
    'Te voy apoyar en todo lo que hagas',
    'Yo se que todo lo que te propongas lo lograras en Dios!',
    'Nuestra primera cita sera fenomenal mi bebe',
    'A donde quisieras ir despues de casarnos?',
    'Me encanta tu penita :)',
    'Por cada linea de codigo que cree me vas a dar un besito si va?. ya vamos por mas de 300 lineas de codigo',
    'Eres mi princesa hermosa',
    'No eres como las otras personas que conozco mi bebe, me encanta como eres, eres unica',
    'Tu eres una preciosa joya, para mi eres la mas brillante persona que he conocido',
    'Yo no se como haces para enamorarme sin hacer nada',
    'Mi bebe te doy gracias por todo.... De verdad, TODO',
    'Compraremos mucha ropa cuando nos casemos',
    'No se porque soy tan acelerado... Apenas tengo 17 jajaja y digo mi edad y no me creo que sea tan joven, de verdad amor JAJA',
    'Cuando nos casemos vamos hacer una oracion para entronar a Dios en nuestro matrimonio y ser muy felices juntos',
    'Caeerte a besos es lo que mas quiero',
    'Si nos casamos nos vamos para una masion eso es mentira que voy a vivir en una casita pequeña jeje :)',
    'Me da pena llevarte cartas a la iglesia bebe.. Prefiero un mensaje de texto',
    'A pesar de todo lo que pase, te amare y te seguire amando por siempre por toda la vida, incluso en el cielo',
    'Nuestro amor es unico bebe, y me encanta que sea asi',
    'Mi cerebro esta seco jajaja no se que mas escribir',
    'Tu sonrisa me encanta lo sabias? una princesa como tu es imposible encontrarmela en la vida',
    'Amor si fuera por mi ya estaria casado contio',
    'Amorcito tu me hackeaste la vida, hiciste que conociera el amor en realidad',
    'Aunque no creas, aprendi mucho de ti...',
    'Quiero que seamos la luz del mundo con Dios y cambiemos al planeta a un lugar mejor',
    'Unos suegros como tus padres es lo mejor jaja se van para caernos a latasos xd',
    'ILOVIUUUUUUUU',
    'Un dia te cantare algo en publico',
    'Eres mi chiquita preciosa',
    'Tengo tu gancheta amorcito, te lo entregare a los 18',
    'Esta sera la mejor aplicacion de telefono que he hecho',
    'Te tratare como la reina que eres',
    'Lo que Dios unio no lo separa el hombre.. Ya sabes amorcito nadie nos va a separar, por adelantado jeje',
    'Mi princesaaaa tendras a un hombre multifacetico :)',
    'Amo tenerte como novia',
    'Siempre veo una belleza natural, y eres tu mi nena',
    'AMOOOO cuando me dices te amo :)',
    'Termine con la mejor persona de este mundo jeje sola para mi',
    'Ya somos legales amor!!! solo que la iglesia no lo sabe jajajajaja',
    'Linea 281 de codigo... MI JOYAAA TE TENGO EN MI CORAZON POR SIEMPRE',
    'No necesito de mil motivos para sonreír, contigo ya es suficiente',
    'Eres una ladrona, porque me has robado el corazon',
    'Me pregunto como es posible que siga asi de enamorado de ti, es lo mejor que me ha podido pasar',
    'Seguro que hay amores imposibles, pero para mi el único amor imposible es aquel en el que no estás tu',
    'Contigo todo me parece romantico',
    'No hay ninguna posibilidad de que un dia deje de amarte',
    'Nunca me cansare de darte las gracias por seguir a mi lado',
    '!!!AMO A DIOS!!! me ha puesto a tu lado y con eso soy feliz, no quiero mas nada solo quiero estar contigo',
    'Eres la mujer que da color a mi vida',
    'Has hecho de mi vida algo emocionante y que merece la pena experimentar',
    'Tu eres el unico paraíso que me interesa',
    'Cuando pienso en el futuro tan solo soy capaz de ver tu rostro',
    'Ahora que te conozco, toda una vida me parece poco tiempo para estar contigo',
    'Quisiera ser veloz como el viento para viajar y poder acariciarte, es que esto de amarte desde lejos es cada vez mas cortante',
    'Te nombro la octava maravilla del mundo, BRITNEY :)',
    'La vida esta formada por elecciones de todo tipo, de todas ellas, la mas bonita has sido tu',
    'Tus ojos son la cosa mas bonita del mundo, no hay mejor obra de arte que les gane en realismo',
    'Si la belleza fuese una gota de agua, tu para mi serias el mas grande de los oceanos',
    'Tu solamente en mi vida siempre estaras, no importa lo que pase, contigo quiero llegar hasta la eternidad',
    'Cuando te echo de menos, no me vienen a la cabeza otras palabras, me vienes a la cabeza solo tu',
    'Quererte y amarte es lo mejor del mundo',
    'What!! me quede loco cuando conoci tanta originalidad en una persona',
    'Es imposible no amarte',
    'Raramente PIENSO TODO EL DIA EN TI',
    'TIAMOOO ILOVEYOU',
    'YA QUIERO TERMINAR LA UNIVERSIDAD PARA ESTAR CON LA MEJOR PERSONA DEL MUNDO',
    'Una vez imagine ser feliz con una persona, no crei que fuera tan real :)',
    'Pura felicidad ocurre en mi vida cuando te veo',
    'AAAA no soporto estar lejos de ti mi bebe',
    'No quiero mas nada, solo estar contigo',
    'DIOS! es una locura lo que siento por ti!',
    'No se porque soy tan celoso',
    'Cuado hablo de ti es como, es una persona increible, es la persona mas bella que pude haber conocido',
    'Esta aplicacion tiene mas de 300 Palabras todas dedicada a ti mi bebe',
    'Tu voz es mi cancion mi nena',
    'La vida sin ti se vuelve aburrida',
    'Me encanta cada detalle de ti',
    'Gracias por estar a mi lado y hacerme feliz',
    'Amo mirarte a los ojos y decirte TE AMO',
    'Es inevitable no enamorarme de ti',
    'Cada segundo de mi silencio en un te amo para ti',
    'Solo espero casarme contigo...'];
    return sentences[Math.floor(Math.random() * sentences.length)];
};

export default getSentence;